// Preview durch <Strg><Shift>v

= Entwickler/innen/handbuch
Gruppe 3
:doctype: book
:toc: left
:sectanchors:
:sectlinks:
:sectnums:
:source-highlighter: coderay
:icons: font
// :kroki-server-url: https://kroki.io

// https://github.com/asciidoctor/asciidoctorj
// https://github.com/asciidoctor/asciidoctor-diagram
// http://de.plantuml.com/classes.html
// http://de.plantuml.com/component.html
// https://github.com/odrotbohm/asciidoctor-plantuml

IMPORTANT: Copyright (C) 2020 - present Jürgen Zimmermann, Hochschule Karlsruhe. +
           Free use of this software is granted under the terms of the
           GNU General Public License (GPL) v3. +
           For the full text of the license, see the http://www.gnu.org/licenses/gpl-3.0.html[license] file.

== Der Applikationsserver

=== Der Applikationsserver im Überblick

bla bla

.Use Cases
[plantuml,use-cases,svg]
----
include::use-cases.puml[]
----

bla bla

.Komponentendiagramm
[plantuml,komponenten,svg]
----
include::komponenten.puml[]
----

=== Die REST-Schnittstelle

bla bla

.Controller für die REST-Schnittstelle
[plantuml,FahrradController,svg]
----
include::FahrradController.puml[]
----

=== Die GraphQL-Schnittstelle

bla bla

.Resolver für die GraphQL-Schnittstelle
[plantuml,FahrradResolver,svg]
----
include::FahrradResolver.puml[]
----

=== Der Anwendungskern

bla bla

.Anwendungskern
[plantuml,FahrradService,svg]
----
include::FahrradService.puml[]
----

=== Klasse für Entities und MongoDB-Dokumente

bla bla

.Entity und Document
[plantuml,Fahrrad,svg]
----
include::Fahrrad.puml[]
----

== Programmierrichtlinien für TypeScript und JavaScript

Für die Programmierung mit *TypeScript* und *JavaScript* wird folgende
Styleguides empfehlenswert:

[horizontal]
_Microsoft_:: https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines
_Angular_:: https://angular.io/docs/ts/latest/guide/style-guide.html
_Google_:: https://google.github.io/styleguide/tsguide.html
_React_:: https://github.com/airbnb/javascript/tree/master/react
