//
// N e t z w e r k   -  V e r b i n d u n g   n o t w e n d i g
//

### Suche alle Fahrraeder
GET {{restUrl}}

### Suche mit vorhandener Fahrrad-ID
GET {{restUrl}}/000000000000000000000001

### Suche mit vorhandener Fahrrad-ID und Versionsnummer
GET {{restUrl}}/000000000000000000000001
If-None-Match: "0"

### Suche mit vorhandener Fahrrad-ID und falscher Versionsnummer
GET {{restUrl}}/000000000000000000000001
If-None-Match: 0

### Suche mit ungueltiger Fahrrad-ID
GET {{restUrl}}/YYYYYYYYYYYYYYYYYYYYYYYY

### Suche mit nicht-vorhandener Fahrrad-ID
GET {{restUrl}}/999999999999999999999999


### Suche mit nicht-vorhandener Property
GET {{restUrl}}?php=true

### Suche mit gueltiger Fahrradart
GET {{restUrl}}?art=MOUNTAINBIKE

### Suche mit gueltigem Gewicht
GET {{restUrl}}?gewicht=13.3

